language: python

dist: xenial

python: "3.6"

env:
  - CONFIG_NAME=config_test.yml

install:
  - pip install -r -q requirements.txt
  - pip install coveralls

script:
  - pylint --rcfile=pylint.conf app
  - coverage run -m pytest -p no:warnings

after_script:
  - coveralls
